version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'devcontainers'
    directory: '.devcontainer'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '.github'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'pip'
    directory: 'vitagen'
    schedule:
      interval: 'daily'
