name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  pull-requests: write
  contents: read

jobs:
  latex:
    uses: ./.github/workflows/shared.yml
    with:
      main_document: resume.tex
      working_directory: "."
