name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  actions: read
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --abbrev=0)
          # Extract changelog for current version with error checking
          if ! CHANGELOG=$(awk '/^#{2}[[:space:]]?\[[0-9]+\.[0-9]+\.[0-9]+\]/{p=NR+3}(NR<=p){print}' CHANGELOG.md); then
            echo "Error extracting changelog"
            exit 1
          fi

          if [ -z "$CHANGELOG" ]; then
            echo "Warning: Empty changelog"
            CHANGELOG="No changelog entries found for this release."
          fi

          gh release create "$TAG" --notes "$CHANGELOG"
