name: shared

on:
  workflow_call:
    inputs:
      main_document:
        description: "Main LaTeX document to build"
        required: true
        type: string
      working_directory:
        description: "Directory containing LaTeX files"
        required: false
        default: "."
        type: string

# Add permissions for PR comments
permissions:
  actions: read
  pull-requests: write
  contents: read

jobs:
  latex-check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup cache keys
      - name: Set installation commands hash
        id: hash
        run: |
          PERL_MODULES="Log::Log4perl YAML::Tiny File::HomeDir Unicode::GCString"
          echo "packages_hash=$(echo $PERL_MODULES | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      # Create local directory for Perl modules and restore cache
      - name: Setup Perl local::lib
        run: |
          echo "Creating Perl local directory..."
          mkdir -p ~/perl5
          eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
          echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc

      - name: Restore cached Perl modules
        id: cache-perl-local
        uses: actions/cache/restore@v4
        with:
          path: ~/perl5
          key: perl-local-${{ steps.hash.outputs.packages_hash }}
          restore-keys: |
            perl-local-

      # Install all dependencies in correct order
      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cpanminus \
            texlive-full \
            chktex

      - name: Install Perl and CPAN dependencies
        run: |
          if [ "${{ steps.cache-perl-local.outputs.cache-hit }}" != 'true' ]; then
            echo "Cache miss - installing Perl dependencies..."
            # Install modules to local directory
            cpanm --local-lib=~/perl5 local::lib
            eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
            
            cpanm --notest Log::Log4perl
            cpanm --notest YAML::Tiny
            cpanm --notest File::HomeDir
            cpanm --notest Unicode::GCString
          else
            echo "Using cached Perl modules from ~/perl5"
            eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
          fi

      # Save cache after installation
      - name: Save Perl modules cache
        if: steps.cache-perl-local.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/perl5
          key: perl-local-${{ steps.hash.outputs.packages_hash }}

      # Verification and processing steps
      - name: Find and validate config files
        id: config
        working-directory: ${{ inputs.working_directory }}
        run: |
          # Check for latexindent config
          if [ -f latexindent.yaml ]; then
            echo "indent_config=latexindent.yaml" >> $GITHUB_OUTPUT
            echo "✅ Found latexindent.yaml"
          else
            echo "⚠️ No latexindent.yaml found, will use default settings"
          fi

          # Check for chktex config
          if [ -f .chktexrc ]; then
            echo "chktex_config=.chktexrc" >> $GITHUB_OUTPUT
            echo "✅ Found .chktexrc"
          else
            echo "⚠️ No .chktexrc found, will use default settings"
          fi

      - name: Find all TeX files
        id: find-tex
        working-directory: ${{ inputs.working_directory }}
        run: |
          files=$(find . -type f \( -name "*.tex" -o -name "*.cls" \) \
            ! -path "./node_modules/*" \
            ! -path "./build/*" \
            ! -path "./dist/*" \
            ! -path "./_minted-*/*" \
            -printf "%P\n")

          echo "$files" > tex_files.txt
          count=$(echo "$files" | wc -l)
          echo "file_count=$count" >> $GITHUB_OUTPUT
          echo "Found $count TeX files to process"

      - name: Run LaTeX formatting check
        id: format
        working-directory: ${{ inputs.working_directory }}
        run: |
          format_errors=0
          total_files=$(cat tex_files.txt | wc -l)

          echo "=== Running Formatter ==="
          while IFS= read -r file; do
            echo -e "\nChecking format of $file..."
            
            # Prepare command with or without config
            if [ "${{ steps.config.outputs.indent_config }}" != "" ]; then
              indent_cmd="latexindent -kv -s -l ${{ steps.config.outputs.indent_config }}"
            else
              indent_cmd="latexindent -kv -s"
            fi
            
            # Run formatting check
            if ! $indent_cmd "$file"; then
              echo "❌ Formatting issues in $file"
              format_errors=$((format_errors + 1))
            else
              echo "✅ $file is properly formatted"
            fi
          done < tex_files.txt

          # Store statistics
          echo "format_errors=$format_errors" >> $GITHUB_OUTPUT
          echo "total_files=$total_files" >> $GITHUB_OUTPUT

          if [ $format_errors -gt 0 ]; then
            echo "❌ Found formatting issues in $format_errors files"
            exit 1
          fi

      - name: Run LaTeX linting
        id: lint
        working-directory: ${{ inputs.working_directory }}
        run: |
          lint_errors=0
          lint_warnings=0

          echo "=== Running Linter ==="
          while IFS= read -r file; do
            echo -e "\nLinting $file..."
            
            # Create directory for log file if it doesn't exist
            log_dir=$(dirname "lint_${file}.log")
            mkdir -p "$log_dir"
            
            # Prepare command with or without config
            if [ "${{ steps.config.outputs.chktex_config }}" != "" ]; then
              chktex_cmd="chktex -l ${{ steps.config.outputs.chktex_config }}"
            else
              chktex_cmd="chktex"
            fi
            
            # Run linting and capture both stdout and stderr
            if ! $chktex_cmd "$file" > "lint_${file}.log" 2>&1; then
              echo "⚠️ Linting issues found in $file"
              cat "lint_${file}.log"
              if grep -q "Error" "lint_${file}.log"; then
                lint_errors=$((lint_errors + 1))
              else
                lint_warnings=$((lint_warnings + 1))
              fi
            else
              echo "✅ No linting issues in $file"
            fi
          done < tex_files.txt

          # Store statistics
          echo "lint_errors=$lint_errors" >> $GITHUB_OUTPUT
          echo "lint_warnings=$lint_warnings" >> $GITHUB_OUTPUT

          if [ $lint_errors -gt 0 ]; then
            echo "❌ Found $lint_errors linting errors"
            exit 1
          fi

          if [ $lint_warnings -gt 0 ]; then
            echo "⚠️ Found $lint_warnings linting warnings"
            exit 1
          fi

      - name: Build PDF with XeLaTeX
        working-directory: ${{ inputs.working_directory }}
        run: |
          latexmk -xelatex \
            -interaction=nonstopmode \
            -file-line-error \
            ${{ inputs.main_document }}

      - name: Upload PDF artifact
        id: upload_pdf
        uses: actions/upload-artifact@v4
        with:
          name: pdf-output
          path: ${{ inputs.working_directory }}/*.pdf
          if-no-files-found: error

      - name: Generate Summary
        if: always()
        env:
          FORMAT_ERRORS: ${{ steps.format.outputs.format_errors }}
          LINT_ERRORS: ${{ steps.lint.outputs.lint_errors }}
          LINT_WARNINGS: ${{ steps.lint.outputs.lint_warnings }}
        run: |
          # Start with a header
          echo "# 📑 LaTeX Build Report" >> $GITHUB_STEP_SUMMARY

          # Add status banner
          if [ "$FORMAT_ERRORS" = "0" ] && [ "$LINT_ERRORS" = "0" ] && [ "$LINT_WARNINGS" = "0" ]; then
            echo "## ✅ Build Status: Successful" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Build Status: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          # Add processing statistics
          echo "## 📊 Processing Statistics" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Count | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Total Files Processed | ${{ steps.find-tex.outputs.file_count }} | ℹ️ |" >> $GITHUB_STEP_SUMMARY

          # Add formatting status with emoji
          if [ "$FORMAT_ERRORS" = "0" ]; then
            echo "| Formatting Issues | 0 | ✅ |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Formatting Issues | $FORMAT_ERRORS | ❌ |" >> $GITHUB_STEP_SUMMARY
          fi

          # Add linting status with emoji
          if [ "$LINT_ERRORS" = "0" ]; then
            echo "| Linting Errors | 0 | ✅ |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Linting Errors | $LINT_ERRORS | ❌ |" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "$LINT_WARNINGS" = "0" ]; then
            echo "| Linting Warnings | 0 | ✅ |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Linting Warnings | $LINT_WARNINGS | ⚠️ |" >> $GITHUB_STEP_SUMMARY
          fi

          # Add artifact information if build succeeded
          if [ "$FORMAT_ERRORS" = "0" ] && [ "$LINT_ERRORS" = "0" ] && [ "$LINT_WARNINGS" = "0" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## 📋 Build Artifacts" >> $GITHUB_STEP_SUMMARY
            echo "✅ PDF has been generated successfully" >> $GITHUB_STEP_SUMMARY
            echo "- The generated PDF is available in the workflow artifacts" >> $GITHUB_STEP_SUMMARY
          fi

          # Add note about errors if any
          if [ "$FORMAT_ERRORS" != "0" ] || [ "$LINT_ERRORS" != "0" ] || [ "$LINT_WARNINGS" != "0" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## ⚠️ Issues Found" >> $GITHUB_STEP_SUMMARY
            echo "Please check the workflow logs for detailed error messages and fix the following:" >> $GITHUB_STEP_SUMMARY
            
            if [ "$FORMAT_ERRORS" != "0" ]; then
              echo "- ❌ Fix formatting issues in $FORMAT_ERRORS files" >> $GITHUB_STEP_SUMMARY
            fi
            
            if [ "$LINT_ERRORS" != "0" ]; then
              echo "- ❌ Fix linting errors in $LINT_ERRORS files" >> $GITHUB_STEP_SUMMARY
            fi
            
            if [ "$LINT_WARNINGS" != "0" ]; then
              echo "- ⚠️ Address linting warnings in $LINT_WARNINGS files" >> $GITHUB_STEP_SUMMARY
            fi
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const artifactName = 'pdf-output';
            const formatErrors = parseInt('${{ steps.format.outputs.format_errors }}') || 0;
            const lintErrors = parseInt('${{ steps.lint.outputs.lint_errors }}') || 0;
            const lintWarnings = parseInt('${{ steps.lint.outputs.lint_warnings }}') || 0;

            const artifactUrl = '${{ steps.upload_pdf.outputs.artifact-url }}';
            let status = '✅ Build Successful';
            let color = '0E8A16'; // green
            let details = '';

            if (formatErrors > 0 || lintErrors > 0 || lintWarnings > 0) {
              status = '❌ Build Failed';
              color = 'D93F0B'; // red
              details = `
              ### Build Statistics
              - Total files processed: ${{ steps.find-tex.outputs.file_count }}
              - Files with formatting issues: ${formatErrors}
              - Files with lint errors: ${lintErrors}
              - Files with lint warnings: ${lintWarnings}
              
              Please check the workflow logs for detailed error messages.
              `;
            } else {
              details = `
              ### 📄 PDF artifact has been generated successfully!
              
              🔗 [Download PDF Artifact](${artifactUrl})
              
              ### Build Statistics
              - Total files processed: ${{ steps.find-tex.outputs.file_count }}
              - All formatting checks passed ✅
              - All lint checks passed ✅
              `;
            }

            const comment = `## ${status}

            ${details}

            [View full workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId})`;

            // Find any existing comments by the bot
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Build');
            });

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              // Create new comment if none exists
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: |
            ${{ inputs.working_directory }}/*.log
            ${{ inputs.working_directory }}/lint_*.log
